# This tmux statusbar config was created by tmuxline.vim
# on Thu, 06 Nov 2025
set -g status on
set -g status-interval 5
set -g status-justify left

# --- General Style ---
set -g status-style "bg=#2e383c,fg=#9da9a0"
set -g message-style "bg=#414b50,fg=#d3c6aa"
set -g message-command-style "bg=#414b50,fg=#d3c6aa"
set -g pane-border-style "fg=#414b50"
set -g pane-active-border-style "fg=#a7c080"

setw -g window-status-separator ""
setw -g window-status-activity-style "none"

# --- Window Titles ---
setw -g window-status-format "#[fg=#859289,bg=#2e383c] #I  #W "
setw -g window-status-current-format "#[fg=#2e383c,bg=#a7c080,bold]#[fg=#272e33,bg=#a7c080] #I  #W #[fg=#a7c080,bg=#2e383c]"

# --- Left Section ---
set -g status-left-length 100
set -g status-left "#[fg=#2e383c,bg=#a7c080,bold]  #[fg=#a7c080,bg=#414b50,nobold]#[fg=#d3c6aa,bg=#414b50] #S #[fg=#414b50,bg=#2e383c]"

# --- Right Section ---

# Update a bit more often so stats feel live
set -g status-interval 5

# Nice prefix/copy indicators from tmux-prefix-highlight
set -g @prefix_highlight_show_copy_mode 'on'
set -g @prefix_highlight_output_prefix ' ⌨ '
set -g @prefix_highlight_copy_mode_attr 'fg=#2e383c,bg=#a7c080,bold'

set -g status-right-length 100
set -g status-right "#[fg=#9da9a0,bg=#414b50] %Y-%m-%d  %H:%M #[fg=#a7c080,bg=#414b50]#[fg=#2e383c,bg=#a7c080,bold] #h "

