set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"

# Change prefix to Ctrl + B
set -g prefix C-b
unbind C-a
bind-key C-b send-prefix

# Change split window - | for horizontal, - for vertical
unbind %
bind | split-window -h 

unbind '"'
bind - split-window -v

# "R" now sources this config
unbind r
bind r source-file ~/.tmux.conf

# JKLH for resizing panes
bind j resize-pane -D 5
bind k resize-pane -U 5
bind l resize-pane -R 5
bind h resize-pane -L 5

bind -r m resize-pane -Z

set -g mouse on

set-window-option -g mode-keys vi

bind-key -T copy-mode-vi 'v' send -X begin-selection # start selecting text with "v"
bind-key -T copy-mode-vi 'y' send -X copy-selection # copy text with "y"

unbind -T copy-mode-vi MouseDragEnd1Pane # don't exit copy mode when dragging with mouse

# remove delay for exiting insert mode with ESC in Neovim
set -sg escape-time 10

# tpm plugin
set -g @plugin 'tmux-plugins/tpm'

# list of tmux plugins
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-copycat'
set -g @plugin 'tmux-plugins/tmux-prefix-highlight'
set -g @plugin 'tmux-plugins/tmux-resurrect' 
set -g @plugin 'toddyamakawa/tmux-scratchpad'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'sainnhe/tmux-fzf'
set -g @plugin 'laktak/extrakto'
set -g @plugin 'tmux-plugins/tmux-sessionist'
set -g @plugin 'fcsonline/tmux-thumbs'
set -g @plugin 'wfxr/tmux-fzf-url'

# Theming
set -g @plugin "2kabhishek/tmux2k"

set -g @tmux2k-theme 'catppuccin'

set -g @tmux2k-icons-only false 

set -g @tmux2k-left-sep 
set -g @tmux2k-right-sep 

set -g @tmux2k-window-list-right-sep 
set -g @tmux2k-window-list-left-sep 

set -g @tmux2k-left-plugins "session cpu ram"
set -g @tmux2k-right-plugins "docker time"
# FZF configuration
set -g @tmux-fzf-launch-key 'F'
set -g @tmux-fzf-options '-p -w 80% -h 80% -m'

# Restore old sessions
set -g @resurrect-capture-pane-contents 'on'
set -g @resurrect-strategy-nvim 'session'
set -g @continuum-restore 'on'
set -g @continuum-save-interval '5' # Save every 5 minutes

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'

set-option -g @scratch-command-key 'Tab'
set -g default-shell /bin/zsh
set-option -g update-environment "PATH"
